import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const ordersRu={
  "orders.eyebrow":"ПРОДАЖИ","orders.title":"Заказы","orders.lead":"Фильтры и подробная декомпозиция финансового результата.","orders.search":"Поиск заказа","orders.number":"Номер заказа","orders.status":"Статус","orders.allStatuses":"Все статусы","orders.pending":"В обработке","orders.dateFrom":"Заказы с даты","orders.dateTo":"Заказы по дату","orders.from":"С","orders.to":"По","orders.product":"Товар","orders.allProducts":"Все товары","orders.profitFrom":"Прибыль от","orders.profitTo":"Прибыль до","orders.loading":"Загрузка…","orders.apply":"Применить","orders.order":"Заказ","orders.date":"Дата","orders.amount":"Сумма","orders.fee":"Комиссия","orders.delivery":"Доставка","orders.profit":"Прибыль","orders.calculation":"Расчёт","orders.complete":"Полный","orders.needsCost":"Нужна себестоимость","orders.empty":"По заданным фильтрам заказов нет.","orders.found":"Найдено","orders.code":"Код","orders.payment":"Оплата","orders.unspecified":"не указана","orders.completed":"Завершён","orders.dateMissing":"дата отсутствует","orders.fallback":"Дата завершения отсутствует — расчёт выполнен по дате создания.","orders.returnRequested":"Запрошен возврат доставки — заказ ещё не считается окончательно возвращённым.","orders.revenue":"Выручка","orders.fees":"Комиссии","orders.variableCosts":"Прочие переменные расходы","orders.operatingProfit":"Операционная прибыль","orders.margin":"Маржа","orders.statusHistory":"История статусов","orders.historyEmpty":"История появится после следующей синхронизации.","orders.lines":"Товарные строки","orders.quantity":"Количество","orders.unitCost":"Себестоимость единицы"
  ,"orders.skuUnmapped":"SKU не сопоставлен","orders.pieces":"шт.","orders.lineRevenue":"выручка","orders.lineCost":"себестоимость","orders.lineFee":"комиссия","orders.lineDelivery":"доставка","orders.lineOther":"прочие"
} as const;
const ordersKk:Record<keyof typeof ordersRu,string>={
  "orders.eyebrow":"САТЫЛЫМДАР","orders.title":"Тапсырыстар","orders.lead":"Қаржылық нәтижені сүзу және толық жіктеу.","orders.search":"Тапсырысты іздеу","orders.number":"Тапсырыс нөмірі","orders.status":"Күйі","orders.allStatuses":"Барлық күйлер","orders.pending":"Өңделуде","orders.dateFrom":"Бастапқы күн","orders.dateTo":"Соңғы күн","orders.from":"Бастап","orders.to":"Дейін","orders.product":"Тауар","orders.allProducts":"Барлық тауарлар","orders.profitFrom":"Пайда бастап","orders.profitTo":"Пайда дейін","orders.loading":"Жүктелуде…","orders.apply":"Қолдану","orders.order":"Тапсырыс","orders.date":"Күні","orders.amount":"Сома","orders.fee":"Комиссия","orders.delivery":"Жеткізу","orders.profit":"Пайда","orders.calculation":"Есеп","orders.complete":"Толық","orders.needsCost":"Өзіндік құн қажет","orders.empty":"Берілген сүзгілер бойынша тапсырыс жоқ.","orders.found":"Табылды","orders.code":"Код","orders.payment":"Төлем","orders.unspecified":"көрсетілмеген","orders.completed":"Аяқталды","orders.dateMissing":"күні жоқ","orders.fallback":"Аяқталу күні жоқ — есеп құру күні бойынша орындалды.","orders.returnRequested":"Жеткізуді қайтару сұралды — тапсырыс әлі толық қайтарылған жоқ.","orders.revenue":"Түсім","orders.fees":"Комиссиялар","orders.variableCosts":"Басқа айнымалы шығындар","orders.operatingProfit":"Операциялық пайда","orders.margin":"Маржа","orders.statusHistory":"Күйлер тарихы","orders.historyEmpty":"Тарих келесі синхрондаудан кейін пайда болады.","orders.lines":"Тауар жолдары","orders.quantity":"Саны","orders.unitCost":"Бірлік өзіндік құны"
  ,"orders.skuUnmapped":"SKU сәйкестендірілмеген","orders.pieces":"дана","orders.lineRevenue":"түсім","orders.lineCost":"өзіндік құн","orders.lineFee":"комиссия","orders.lineDelivery":"жеткізу","orders.lineOther":"басқа"
};
const productsRu={
  "products.eyebrow":"КАТАЛОГ","products.title":"Товары","products.lead":"Продажи, история себестоимости и Coverage по SKU.","products.import":"Импорт CSV/XLSX","products.search":"Поиск по SKU или названию","products.all":"Все товары","products.profitable":"Прибыльные","products.loss":"Убыточные","products.missing":"Без себестоимости","products.archived":"Архивные","products.sort":"Сортировка товаров","products.nameAsc":"Название: А–Я","products.skuAsc":"SKU: А–Я","products.unitsDesc":"Продажи: больше","products.revenueDesc":"Выручка: больше","products.profitDesc":"Прибыль: больше","products.profitAsc":"Прибыль: меньше","products.marginDesc":"Маржа: больше","products.coverageAsc":"Coverage: меньше","products.product":"Товар","products.sales":"Продажи","products.revenue":"Выручка","products.expenses":"Расходы","products.profit":"Прибыль","products.margin":"Маржа","products.status":"Статус","products.archive":"Архив","products.active":"Активен","products.direct":"Прямые","products.allocated":"распределённые","products.checking":"Проверяем файл…","products.importError":"Ошибка импорта","products.applied":"Применено строк","products.applyError":"Не удалось применить импорт","products.costAdded":"Себестоимость добавлена","products.error":"Ошибка","products.statusError":"Не удалось изменить статус товара","products.movedArchive":"Товар перемещён в архив","products.restored":"Товар возвращён в активные","products.seriesError":"Не удалось загрузить динамику товара"
} as const;
const productsKk:Record<keyof typeof productsRu,string>={
  "products.eyebrow":"КАТАЛОГ","products.title":"Тауарлар","products.lead":"SKU бойынша сатылым, өзіндік құн тарихы және Coverage.","products.import":"CSV/XLSX импорты","products.search":"SKU немесе атауы бойынша іздеу","products.all":"Барлық тауарлар","products.profitable":"Пайдалы","products.loss":"Залалды","products.missing":"Өзіндік құнсыз","products.archived":"Мұрағатта","products.sort":"Тауарларды сұрыптау","products.nameAsc":"Атауы: А–Я","products.skuAsc":"SKU: А–Я","products.unitsDesc":"Сатылым: көп","products.revenueDesc":"Түсім: көп","products.profitDesc":"Пайда: көп","products.profitAsc":"Пайда: аз","products.marginDesc":"Маржа: көп","products.coverageAsc":"Coverage: аз","products.product":"Тауар","products.sales":"Сатылым","products.revenue":"Түсім","products.expenses":"Шығындар","products.profit":"Пайда","products.margin":"Маржа","products.status":"Күйі","products.archive":"Мұрағат","products.active":"Белсенді","products.direct":"Тікелей","products.allocated":"бөлінген","products.checking":"Файл тексерілуде…","products.importError":"Импорт қатесі","products.applied":"Қолданылған жолдар","products.applyError":"Импортты қолдану мүмкін болмады","products.costAdded":"Өзіндік құн қосылды","products.error":"Қате","products.statusError":"Тауар күйін өзгерту мүмкін болмады","products.movedArchive":"Тауар мұрағатқа көшірілді","products.restored":"Тауар белсендіге қайтарылды","products.seriesError":"Тауар динамикасын жүктеу мүмкін болмады"
};
const productDetailRu={
  "product.restore":"Вернуть в активные","product.archiveAction":"Архивировать","product.dynamics":"Динамика товара","product.allPeriod":"За весь период","product.revenue":"Выручка","product.profit":"Прибыль","product.loading":"Загрузка динамики…","product.chartLabel":"Выручка и прибыль товара по дням","product.emptySeries":"За выбранный период продаж и расходов по товару нет.","product.cost":"Себестоимость","product.effectiveFrom":"Действует с","product.add":"Добавить","product.costHistory":"История себестоимости","product.from":"с","product.historyEmpty":"История пока пуста.","import.preview":"Предпросмотр импорта","import.rows":"Строк","import.matched":"найдено","import.unmatched":"не сопоставлено","import.errors":"ошибки","import.duplicates":"дубли","import.apply":"Применить","import.changes":"изменений","import.row":"Строка","import.cost":"Себестоимость","import.date":"Дата","import.status":"Статус"
} as const;
const productDetailKk:Record<keyof typeof productDetailRu,string>={
  "product.restore":"Белсендіге қайтару","product.archiveAction":"Мұрағаттау","product.dynamics":"Тауар динамикасы","product.allPeriod":"Барлық кезеңде","product.revenue":"Түсім","product.profit":"Пайда","product.loading":"Динамика жүктелуде…","product.chartLabel":"Тауардың күндер бойынша түсімі мен пайдасы","product.emptySeries":"Таңдалған кезеңде тауар бойынша сатылым мен шығын жоқ.","product.cost":"Өзіндік құн","product.effectiveFrom":"Басталу күні","product.add":"Қосу","product.costHistory":"Өзіндік құн тарихы","product.from":"бастап","product.historyEmpty":"Тарих әзірге бос.","import.preview":"Импортты алдын ала қарау","import.rows":"Жолдар","import.matched":"табылды","import.unmatched":"сәйкестенбеді","import.errors":"қателер","import.duplicates":"қайталанғандар","import.apply":"Қолдану","import.changes":"өзгеріс","import.row":"Жол","import.cost":"Өзіндік құн","import.date":"Күні","import.status":"Күйі"
};
const financeRu={
  "financial.checkingFile":"Проверяем файл…","financial.readError":"Не удалось прочитать файл","financial.appliedRows":"Применено строк","financial.applyError":"Не удалось применить импорт","financial.expensesImport":"Импорт расходов","financial.feesImport":"Импорт фактических комиссий","financial.importLead":"CSV/XLSX до 5 МБ. Изменения применятся только после подтверждения.","financial.downloadTemplate":"Скачать шаблон XLSX","financial.checking":"Проверяем…","financial.chooseFile":"Выбрать файл","financial.rows":"Строк","financial.newRows":"новых","financial.updates":"обновлений","financial.duplicates":"дублей","financial.errors":"ошибок","financial.apply":"Применить","financial.changes":"изменений","financial.row":"Строка","financial.amount":"Сумма","financial.dateLink":"Дата / связь","financial.status":"Статус",
  "expenses.added":"Расход добавлен","expenses.addError":"Не удалось добавить расход","expenses.eyebrow":"ЗАТРАТЫ","expenses.title":"Расходы","expenses.lead":"Реклама, упаковка, фулфилмент, сервисы и прочие затраты.","expenses.advertising":"Реклама","expenses.packaging":"Упаковка","expenses.fulfillment":"Фулфилмент","expenses.services":"Сервисы","expenses.other":"Прочее","expenses.amountPlaceholder":"Сумма, ₸","expenses.periodEnd":"Конец периода","expenses.periodEndHint":"Необязательно: конец периода расхода","expenses.organizationAll":"Вся организация","expenses.order":"Заказ","expenses.noOrder":"Без привязки к заказу","expenses.comment":"Комментарий","expenses.add":"Добавить","expenses.datePeriod":"Дата / период","expenses.type":"Тип","expenses.link":"Привязка","expenses.organization":"Организация","expenses.delete":"Удалить",
  "fees.created":"Правило комиссии создано","fees.checkParams":"Проверьте параметры правила","fees.endDateRequired":"Укажите дату окончания правила","fees.updated":"Период действия правила обновлён","fees.endError":"Не удалось завершить правило","fees.eyebrow":"ФИНАНСОВЫЕ ПРАВИЛА","fees.title":"Комиссии","fees.lead":"Фактическое удержание имеет приоритет над версионным правилом.","fees.scopeOrganization":"Для организации","fees.scopeCategory":"Для категории","fees.scopeProduct":"Для товара","fees.chooseCategory":"Выберите категорию","fees.percentage":"Процент","fees.fixed":"Фиксированная сумма","fees.value":"Значение","fees.effectiveTo":"Действует по","fees.create":"Создать правило","fees.scope":"Область","fees.assignment":"Назначение","fees.type":"Тип","fees.effectiveFrom":"Действует с","fees.finish":"Завершить","fees.productDeleted":"Товар удалён","fees.allProducts":"Все товары","fees.unlimited":"Бессрочно"
} as const;
const financeKk:Record<keyof typeof financeRu,string>={
  "financial.checkingFile":"Файл тексерілуде…","financial.readError":"Файлды оқу мүмкін болмады","financial.appliedRows":"Қолданылған жолдар","financial.applyError":"Импортты қолдану мүмкін болмады","financial.expensesImport":"Шығындар импорты","financial.feesImport":"Нақты комиссиялар импорты","financial.importLead":"5 МБ-қа дейінгі CSV/XLSX. Өзгерістер расталғаннан кейін ғана қолданылады.","financial.downloadTemplate":"XLSX үлгісін жүктеу","financial.checking":"Тексерілуде…","financial.chooseFile":"Файлды таңдау","financial.rows":"Жолдар","financial.newRows":"жаңа","financial.updates":"жаңартулар","financial.duplicates":"қайталанғандар","financial.errors":"қателер","financial.apply":"Қолдану","financial.changes":"өзгеріс","financial.row":"Жол","financial.amount":"Сома","financial.dateLink":"Күні / байланысы","financial.status":"Күйі",
  "expenses.added":"Шығын қосылды","expenses.addError":"Шығынды қосу мүмкін болмады","expenses.eyebrow":"ШЫҒЫНДАР","expenses.title":"Шығындар","expenses.lead":"Жарнама, қаптама, фулфилмент, сервистер және басқа шығындар.","expenses.advertising":"Жарнама","expenses.packaging":"Қаптама","expenses.fulfillment":"Фулфилмент","expenses.services":"Сервистер","expenses.other":"Басқа","expenses.amountPlaceholder":"Сома, ₸","expenses.periodEnd":"Кезеңнің соңы","expenses.periodEndHint":"Міндетті емес: шығын кезеңінің соңғы күні","expenses.organizationAll":"Бүкіл ұйым","expenses.order":"Тапсырыс","expenses.noOrder":"Тапсырысқа байланыссыз","expenses.comment":"Түсініктеме","expenses.add":"Қосу","expenses.datePeriod":"Күні / кезеңі","expenses.type":"Түрі","expenses.link":"Байланысы","expenses.organization":"Ұйым","expenses.delete":"Жою",
  "fees.created":"Комиссия ережесі құрылды","fees.checkParams":"Ереже параметрлерін тексеріңіз","fees.endDateRequired":"Ереженің аяқталу күнін көрсетіңіз","fees.updated":"Ереженің қолданылу кезеңі жаңартылды","fees.endError":"Ережені аяқтау мүмкін болмады","fees.eyebrow":"ҚАРЖЫЛЫҚ ЕРЕЖЕЛЕР","fees.title":"Комиссиялар","fees.lead":"Нақты ұсталым нұсқаланған ережеден басым болады.","fees.scopeOrganization":"Ұйым үшін","fees.scopeCategory":"Санат үшін","fees.scopeProduct":"Тауар үшін","fees.chooseCategory":"Санатты таңдаңыз","fees.percentage":"Пайыз","fees.fixed":"Тұрақты сома","fees.value":"Мәні","fees.effectiveTo":"Аяқталу күні","fees.create":"Ереже құру","fees.scope":"Ауқымы","fees.assignment":"Мақсаты","fees.type":"Түрі","fees.effectiveFrom":"Басталу күні","fees.finish":"Аяқтау","fees.productDeleted":"Тауар жойылған","fees.allProducts":"Барлық тауарлар","fees.unlimited":"Мерзімсіз"
};
const exportsRu={
  "exports.eyebrow":"ОТЧЁТЫ","exports.title":"Экспорт","exports.lead":"Выгрузки создаются в фоне; ссылка действует один час.","exports.products":"Прибыль по товарам","exports.orders":"Заказы","exports.missingCosts":"Товары без себестоимости","exports.abc":"ABC-анализ","exports.from":"С","exports.to":"По","exports.completeCosts":"Только продажи с полной себестоимостью","exports.creating":"Создаём…","exports.create":"Сформировать","exports.createError":"Не удалось создать выгрузку","exports.rows":"строк","exports.download":"Скачать","exports.queued":"В очереди","exports.running":"Формируется","exports.succeeded":"Готово","exports.failed":"Ошибка","exports.expired":"Ссылка истекла","exports.timeout":"Формирование продолжается. Статус обновится при возврате на экран.","exports.empty":"Созданные в этой вкладке выгрузки появятся здесь."
} as const;
const exportsKk:Record<keyof typeof exportsRu,string>={
  "exports.eyebrow":"ЕСЕПТЕР","exports.title":"Экспорт","exports.lead":"Жүктемелер фонда жасалады; сілтеме бір сағат жарамды.","exports.products":"Тауарлар бойынша пайда","exports.orders":"Тапсырыстар","exports.missingCosts":"Өзіндік құнсыз тауарлар","exports.abc":"ABC-талдау","exports.from":"Бастап","exports.to":"Дейін","exports.completeCosts":"Тек толық өзіндік құны бар сатылымдар","exports.creating":"Жасалуда…","exports.create":"Қалыптастыру","exports.createError":"Жүктемені жасау мүмкін болмады","exports.rows":"жол","exports.download":"Жүктеу","exports.queued":"Кезекте","exports.running":"Қалыптастырылуда","exports.succeeded":"Дайын","exports.failed":"Қате","exports.expired":"Сілтеменің мерзімі аяқталды","exports.timeout":"Қалыптастыру жалғасуда. Экранға оралғанда күйі жаңартылады.","exports.empty":"Осы бетте жасалған жүктемелер мұнда көрсетіледі."
};
const settingsRu={
  "settings.inviteDelivered":"Приглашение отправлено по email","settings.inviteCreated":"Приглашение создано — передайте ссылку пользователю","settings.inviteError":"Не удалось создать приглашение","settings.roleChanged":"Роль изменена","settings.roleError":"Не удалось изменить роль","settings.removeConfirm":"Удалить пользователя из организации?","settings.memberRemoved":"Участник удалён","settings.memberRemoveError":"Не удалось удалить участника","settings.inviteCancelled":"Приглашение отменено","settings.inviteCancelError":"Не удалось отменить приглашение","settings.telegramUnavailable":"Telegram bot пока не настроен","settings.testSent":"Тест отправлен","settings.testError":"Не удалось отправить тест","settings.saved":"Настройки организации сохранены","settings.saveError":"Не удалось сохранить настройки","settings.exactName":"Введите точное название организации","settings.deleteError":"Удаление не выполнено",
  "settings.eyebrow":"ОРГАНИЗАЦИЯ","settings.title":"Настройки","settings.planWord":"тариф","settings.organization":"Организация","settings.name":"Название","settings.timeZone":"Часовой пояс","settings.currency":"Валюта","settings.allocate":"Распределять общеорганизационные расходы по выручке товаров","settings.allocateHint":"Общий результат не изменится. Настройка влияет только на прибыльность товаров и ABC.","settings.save":"Сохранить","settings.plan":"Тариф","settings.planLimits":"Trial: 2 пользователя · Start: 3 · Pro: 10 · Business: 30.","settings.trialUntil":"Trial до","settings.telegram":"Telegram","settings.status":"Статус","settings.checking":"Проверяем…","settings.telegramActive":"Подключён","settings.telegramPending":"Ожидает подключения","settings.telegramNotLinked":"Не подключён","settings.sendTest":"Отправить тест","settings.linkTelegram":"Связать Telegram","settings.manageRequired":"Для управления нужны права Owner или Admin.","settings.codeValid":"Код действует 15 минут","settings.openTelegram":"Открыть Telegram","settings.notificationRules":"Правила уведомлений","settings.missingCost":"Нет себестоимости","settings.negativeMargin":"Отрицательная маржа","settings.syncError":"Ошибка синхронизации",
  "settings.members":"Пользователи и роли","settings.roleOwner":"Владелец","settings.roleAdmin":"Администратор","settings.roleAnalyst":"Аналитик","settings.roleViewer":"Наблюдатель","settings.remove":"Удалить","settings.invite":"Пригласить","settings.inviteLink":"Ссылка приглашения","settings.until":"до","settings.cancel":"Отменить","settings.deleteOrganization":"Удаление организации","settings.deleteWarning":"Будут безвозвратно удалены заказы, товары, расходы, выгрузки, интеграции и участники. Если это ваша единственная организация, аккаунт также будет удалён.","settings.enterNamePrefix":"Введите «","settings.enterNameSuffix":"»","settings.currentPassword":"Текущий пароль","settings.deleting":"Удаляем…","settings.deleteAction":"Удалить организацию и данные"
} as const;
const settingsKk:Record<keyof typeof settingsRu,string>={
  "settings.inviteDelivered":"Шақыру email арқылы жіберілді","settings.inviteCreated":"Шақыру жасалды — сілтемені пайдаланушыға жіберіңіз","settings.inviteError":"Шақыруды жасау мүмкін болмады","settings.roleChanged":"Рөл өзгертілді","settings.roleError":"Рөлді өзгерту мүмкін болмады","settings.removeConfirm":"Пайдаланушыны ұйымнан жою керек пе?","settings.memberRemoved":"Қатысушы жойылды","settings.memberRemoveError":"Қатысушыны жою мүмкін болмады","settings.inviteCancelled":"Шақыру жойылды","settings.inviteCancelError":"Шақыруды жою мүмкін болмады","settings.telegramUnavailable":"Telegram боты әзірге бапталмаған","settings.testSent":"Тест жіберілді","settings.testError":"Тестті жіберу мүмкін болмады","settings.saved":"Ұйым баптаулары сақталды","settings.saveError":"Баптауларды сақтау мүмкін болмады","settings.exactName":"Ұйым атауын дәл енгізіңіз","settings.deleteError":"Жою орындалмады",
  "settings.eyebrow":"ҰЙЫМ","settings.title":"Баптаулар","settings.planWord":"тариф","settings.organization":"Ұйым","settings.name":"Атауы","settings.timeZone":"Уақыт белдеуі","settings.currency":"Валюта","settings.allocate":"Жалпы ұйымдық шығындарды тауар түсімі бойынша бөлу","settings.allocateHint":"Жалпы нәтиже өзгермейді. Баптау тек тауарлардың пайдалылығы мен ABC-ге әсер етеді.","settings.save":"Сақтау","settings.plan":"Тариф","settings.planLimits":"Trial: 2 пайдаланушы · Start: 3 · Pro: 10 · Business: 30.","settings.trialUntil":"Trial аяқталуы","settings.telegram":"Telegram","settings.status":"Күйі","settings.checking":"Тексерілуде…","settings.telegramActive":"Қосылған","settings.telegramPending":"Қосылуды күтуде","settings.telegramNotLinked":"Қосылмаған","settings.sendTest":"Тест жіберу","settings.linkTelegram":"Telegram-ды қосу","settings.manageRequired":"Басқару үшін Owner немесе Admin құқығы қажет.","settings.codeValid":"Код 15 минут жарамды","settings.openTelegram":"Telegram-ды ашу","settings.notificationRules":"Хабарландыру ережелері","settings.missingCost":"Өзіндік құн жоқ","settings.negativeMargin":"Теріс маржа","settings.syncError":"Синхрондау қатесі",
  "settings.members":"Пайдаланушылар және рөлдер","settings.roleOwner":"Иесі","settings.roleAdmin":"Әкімші","settings.roleAnalyst":"Талдаушы","settings.roleViewer":"Бақылаушы","settings.remove":"Жою","settings.invite":"Шақыру","settings.inviteLink":"Шақыру сілтемесі","settings.until":"дейін","settings.cancel":"Болдырмау","settings.deleteOrganization":"Ұйымды жою","settings.deleteWarning":"Тапсырыстар, тауарлар, шығындар, жүктемелер, интеграциялар және қатысушылар қайтарымсыз жойылады. Бұл жалғыз ұйымыңыз болса, тіркелгі де жойылады.","settings.enterNamePrefix":"«","settings.enterNameSuffix":"» атауын енгізіңіз","settings.currentPassword":"Ағымдағы құпиясөз","settings.deleting":"Жойылуда…","settings.deleteAction":"Ұйым мен деректерді жою"
};
const kaspiRu={
  "kaspi.operationError":"Операция не выполнена","kaspi.loadError":"Не удалось загрузить подключения Kaspi","kaspi.connected":"Магазин подключён","kaspi.syncQueued":"Синхронизация поставлена в очередь","kaspi.tokenValid":"Токен действителен","kaspi.newTokenPrompt":"Новый API-токен для","kaspi.tokenReplaced":"Токен заменён","kaspi.disconnectConfirmPrefix":"Отключить магазин","kaspi.disconnectConfirmSuffix":"Исторические заказы сохранятся.","kaspi.disconnected":"Магазин отключён","kaspi.eyebrow":"ИНТЕГРАЦИИ","kaspi.title":"Kaspi Магазины","kaspi.plan":"Тариф","kaspi.connectedCount":"подключено","kaspi.of":"из","kaspi.securityLead":"Токены шифруются и обратно не отображаются.","kaspi.status":"Статус","kaspi.lastVerification":"Последняя проверка","kaspi.lastSync":"Последняя синхронизация","kaspi.lastJob":"Последнее задание","kaspi.orders":"заказов","kaspi.safeError":"Безопасная ошибка","kaspi.sync":"Синхронизировать","kaspi.verify":"Проверить","kaspi.replaceToken":"Заменить token","kaspi.disconnect":"Отключить","kaspi.connectTitle":"Подключить магазин","kaspi.storeName":"Название магазина","kaspi.storeExample":"Например, Основной магазин","kaspi.apiToken":"API-токен Kaspi","kaspi.tokenPlaceholder":"Токен из кабинета продавца","kaspi.checking":"Проверяем…","kaspi.verifyConnect":"Проверить и подключить","kaspi.empty":"Подключённых магазинов пока нет.","kaspi.pendingVerification":"Ожидает проверки","kaspi.active":"Активен","kaspi.requiresAttention":"Требует внимания","kaspi.disabled":"Отключён","kaspi.queued":"В очереди","kaspi.running":"Выполняется","kaspi.succeeded":"Завершено","kaspi.retryScheduled":"Повтор запланирован"
} as const;
const kaspiKk:Record<keyof typeof kaspiRu,string>={
  "kaspi.operationError":"Операция орындалмады","kaspi.loadError":"Kaspi қосылымдарын жүктеу мүмкін болмады","kaspi.connected":"Дүкен қосылды","kaspi.syncQueued":"Синхрондау кезекке қойылды","kaspi.tokenValid":"Токен жарамды","kaspi.newTokenPrompt":"Жаңа API-токен","kaspi.tokenReplaced":"Токен ауыстырылды","kaspi.disconnectConfirmPrefix":"Дүкенді ажырату","kaspi.disconnectConfirmSuffix":"Тарихи тапсырыстар сақталады.","kaspi.disconnected":"Дүкен ажыратылды","kaspi.eyebrow":"ИНТЕГРАЦИЯЛАР","kaspi.title":"Kaspi дүкендері","kaspi.plan":"Тариф","kaspi.connectedCount":"қосылған","kaspi.of":"ішінен","kaspi.securityLead":"Токендер шифрланады және қайта көрсетілмейді.","kaspi.status":"Күйі","kaspi.lastVerification":"Соңғы тексеру","kaspi.lastSync":"Соңғы синхрондау","kaspi.lastJob":"Соңғы тапсырма","kaspi.orders":"тапсырыс","kaspi.safeError":"Қауіпсіз қате","kaspi.sync":"Синхрондау","kaspi.verify":"Тексеру","kaspi.replaceToken":"Токенді ауыстыру","kaspi.disconnect":"Ажырату","kaspi.connectTitle":"Дүкенді қосу","kaspi.storeName":"Дүкен атауы","kaspi.storeExample":"Мысалы, Негізгі дүкен","kaspi.apiToken":"Kaspi API-токені","kaspi.tokenPlaceholder":"Сатушы кабинетіндегі токен","kaspi.checking":"Тексерілуде…","kaspi.verifyConnect":"Тексеру және қосу","kaspi.empty":"Қосылған дүкендер әзірге жоқ.","kaspi.pendingVerification":"Тексеруді күтуде","kaspi.active":"Белсенді","kaspi.requiresAttention":"Назар аудару қажет","kaspi.disabled":"Ажыратылған","kaspi.queued":"Кезекте","kaspi.running":"Орындалуда","kaspi.succeeded":"Аяқталды","kaspi.retryScheduled":"Қайталау жоспарланды"
};
const abcRu={
  "abc.eyebrow":"АССОРТИМЕНТ","abc.title":"ABC-анализ","abc.lead":"Группы A/B/C по накопительному вкладу 80/15/5.","abc.metric":"Метрика ABC-анализа","abc.operatingProfit":"Операционная прибыль","abc.grossProfit":"Валовая прибыль","abc.revenue":"Выручка","abc.units":"Количество","abc.group":"Группа","abc.product":"Товар","abc.value":"Значение","abc.expenses":"Расходы","abc.profit":"Прибыль","abc.cumulative":"Накопительно","abc.loading":"Загрузка ABC-анализа…","abc.error":"Не удалось загрузить ABC-анализ","abc.empty":"За выбранный период данных для ABC-анализа нет."
} as const;
const abcKk:Record<keyof typeof abcRu,string>={
  "abc.eyebrow":"АССОРТИМЕНТ","abc.title":"ABC-талдау","abc.lead":"Жинақталған үлесі 80/15/5 бойынша A/B/C топтары.","abc.metric":"ABC-талдау метрикасы","abc.operatingProfit":"Операциялық пайда","abc.grossProfit":"Жалпы пайда","abc.revenue":"Түсім","abc.units":"Саны","abc.group":"Топ","abc.product":"Тауар","abc.value":"Мәні","abc.expenses":"Шығындар","abc.profit":"Пайда","abc.cumulative":"Жинақталған","abc.loading":"ABC-талдау жүктелуде…","abc.error":"ABC-талдауды жүктеу мүмкін болмады","abc.empty":"Таңдалған кезеңде ABC-талдау үшін дерек жоқ."
};
const adminRu={
  "admin.operationError":"Операция не выполнена","admin.saved":"Изменения сохранены","admin.loadError":"Не удалось загрузить данные SaaS Admin","admin.blockReason":"Причина блокировки без персональных данных и секретов:","admin.subscriptionReason":"Причина приостановки подписки без персональных данных и секретов:","admin.eyebrow":"SAAS ADMIN","admin.title":"Управление платформой","admin.lead":"Организации, инциденты синхронизации, feature flags и системный аудит.","admin.organizations":"Организации","admin.tenants":"организаций","admin.organization":"Организация","admin.plan":"Тариф","admin.status":"Статус","admin.subscription":"Подписка","admin.users":"Пользователи","admin.sync":"Sync","admin.activity":"Активность","admin.noData":"нет данных","admin.active":"Активна","admin.suspended":"Заблокирована","admin.subscriptionTrial":"Пробный период","admin.subscriptionActive":"Активна","admin.subscriptionSuspended":"Приостановлена","admin.subscriptionExpired":"Истекла","admin.pauseSubscription":"Приостановить подписку","admin.resumeSubscription":"Возобновить подписку","admin.block":"Заблокировать","admin.activate":"Активировать","admin.flags":"Feature flags","admin.selected":"Выбранная организация","admin.enabled":"Включено","admin.disabled":"Отключено","admin.audit":"Системный аудит","admin.noActions":"Действий пока нет.","admin.jobs":"Sync jobs и инциденты","admin.noTokenAccess":"Без доступа к Kaspi token","admin.created":"Создано","admin.attempts":"Попытки","admin.orders":"Заказы","admin.safeError":"Безопасная ошибка","admin.retry":"Повторить","admin.loading":"Загрузка…","admin.queued":"В очереди","admin.running":"Выполняется","admin.succeeded":"Завершено","admin.retryScheduled":"Повтор запланирован","admin.requiresAttention":"Требует внимания",
  "table.product":"Товар","table.revenue":"Выручка","table.profit":"Прибыль","table.margin":"Маржа"
} as const;
const adminKk:Record<keyof typeof adminRu,string>={
  "admin.operationError":"Операция орындалмады","admin.saved":"Өзгерістер сақталды","admin.loadError":"SaaS Admin деректерін жүктеу мүмкін болмады","admin.blockReason":"Жеке деректер мен құпияларсыз бұғаттау себебі:","admin.subscriptionReason":"Жеке деректер мен құпияларсыз жазылымды тоқтату себебі:","admin.eyebrow":"SAAS ADMIN","admin.title":"Платформаны басқару","admin.lead":"Ұйымдар, синхрондау оқиғалары, feature flags және жүйелік аудит.","admin.organizations":"Ұйымдар","admin.tenants":"ұйым","admin.organization":"Ұйым","admin.plan":"Тариф","admin.status":"Күйі","admin.subscription":"Жазылым","admin.users":"Пайдаланушылар","admin.sync":"Sync","admin.activity":"Белсенділік","admin.noData":"дерек жоқ","admin.active":"Белсенді","admin.suspended":"Бұғатталған","admin.subscriptionTrial":"Сынақ кезеңі","admin.subscriptionActive":"Белсенді","admin.subscriptionSuspended":"Тоқтатылған","admin.subscriptionExpired":"Мерзімі өткен","admin.pauseSubscription":"Жазылымды тоқтату","admin.resumeSubscription":"Жазылымды жалғастыру","admin.block":"Бұғаттау","admin.activate":"Белсендіру","admin.flags":"Feature flags","admin.selected":"Таңдалған ұйым","admin.enabled":"Қосылған","admin.disabled":"Өшірілген","admin.audit":"Жүйелік аудит","admin.noActions":"Әрекеттер әзірге жоқ.","admin.jobs":"Sync тапсырмалары мен оқиғалар","admin.noTokenAccess":"Kaspi token-ге қолжетімсіз","admin.created":"Құрылды","admin.attempts":"Әрекеттер","admin.orders":"Тапсырыстар","admin.safeError":"Қауіпсіз қате","admin.retry":"Қайталау","admin.loading":"Жүктелуде…","admin.queued":"Кезекте","admin.running":"Орындалуда","admin.succeeded":"Аяқталды","admin.retryScheduled":"Қайталау жоспарланды","admin.requiresAttention":"Назар аудару қажет",
  "table.product":"Тауар","table.revenue":"Түсім","table.profit":"Пайда","table.margin":"Маржа"
};

export const ru = {
  ...ordersRu,
  ...productsRu,
  ...productDetailRu,
  ...financeRu,
  ...exportsRu,
  ...settingsRu,
  ...kaspiRu,
  ...abcRu,
  ...adminRu,
  "brand.name": "Seller Finance",
  "common.wait": "Подождите…",
  "common.logout": "выйти",
  "common.create": "Создать",
  "auth.login.title": "Войти",
  "auth.login.lead": "Управляйте прибылью и себестоимостью в одном месте.",
  "auth.login.submit": "Войти",
  "auth.register.title": "Создать аккаунт",
  "auth.register.lead": "Создайте защищённое рабочее пространство продавца.",
  "auth.register.submit": "Зарегистрироваться",
  "auth.register.name": "Ваше имя",
  "auth.register.organization": "Название организации",
  "auth.email": "Email",
  "auth.password": "Пароль",
  "auth.forgot.title": "Восстановить пароль",
  "auth.forgot.lead": "Отправим одноразовую ссылку, если аккаунт существует.",
  "auth.forgot.submit": "Отправить инструкцию",
  "auth.forgot.link": "Забыли пароль?",
  "auth.forgot.success": "Если аккаунт существует, инструкция отправлена на email.",
  "auth.confirm.success": "Проверьте почту и подтвердите email.",
  "auth.confirm.deliveryFailed":"Аккаунт создан, но письмо пока не доставлено. Повторите отправку.","auth.confirm.resend":"Отправить письмо ещё раз","auth.confirm.resent":"Если аккаунт ожидает подтверждения, письмо отправлено повторно.",
  "auth.switch.login": "Уже есть аккаунт? Войти",
  "auth.switch.register": "Нет аккаунта? Зарегистрироваться",
  "auth.switch.back": "Вернуться ко входу",
  "auth.error": "Ошибка авторизации",
  "auth.session.error": "Сессия не создана",
  "auth.hero.eyebrow": "Финансы маркетплейса без слепых зон",
  "auth.hero.title": "Знайте реальную прибыль каждого заказа и товара.",
  "demo.banner.title":"Demo-режим","demo.banner.body":"Используйте только вымышленные данные. Подключение реального Kaspi отключено.","demo.auth.title":"Публичная демонстрация","demo.auth.body":"Эта среда не предназначена для реальных данных продавцов, покупателей или действующих Kaspi token.","demo.auth.consent":"Я буду использовать только вымышленные тестовые данные.",
  "auth.hero.lead": "Себестоимость, комиссии, доставка и расходы — в едином расчёте.",
  "reset.title": "Новый пароль",
  "reset.submit": "Сохранить пароль",
  "reset.success": "Пароль изменён. Теперь можно войти.",
  "reset.error": "Ссылка недействительна или пароль не соответствует требованиям.",
  "nav.dashboard": "Обзор",
  "nav.products": "Товары",
  "nav.orders": "Заказы",
  "nav.abc": "ABC-анализ",
  "nav.exports": "Экспорт",
  "nav.integrations": "Интеграции",
  "nav.expenses": "Расходы",
  "nav.fees": "Комиссии",
  "nav.settings": "Настройки",
  "nav.admin": "SaaS Admin",
  "nav.analytics": "АНАЛИТИКА",
  "nav.management": "УПРАВЛЕНИЕ",
  "plan.trial": "Тариф Trial",
  "plan.pilot": "Пилотный период",
  "plan.organization": "1 организация",
  "header.menu": "Открыть меню",
  "header.organization": "Организация",
  "header.createOrganization": "Создать организацию",
  "header.organizationPrompt": "Название новой организации",
  "header.organizationCreateError": "Не удалось создать организацию",
  "language.ru": "Русский",
  "language.kk": "Қазақша",
  "dashboard.title":"Финансовый обзор","dashboard.lead":"Главное о продажах и прибыли за выбранный период.","dashboard.sync":"Синхронизировать","dashboard.today":"Сегодня","dashboard.yesterday":"Вчера","dashboard.days7":"Последние 7 дней","dashboard.days30":"Последние 30 дней","dashboard.days90":"Последние 90 дней","dashboard.currentMonth":"Текущий месяц","dashboard.previousMonth":"Предыдущий месяц","dashboard.custom":"Произвольный период","dashboard.periodFrom":"Начало периода","dashboard.periodTo":"Конец периода","dashboard.completeCosts":"Только продажи с полной себестоимостью","dashboard.loaded":"Данные загружены из PostgreSQL","dashboard.preliminary":"Прибыль предварительная","dashboard.fillCosts":"Заполнить себестоимость","dashboard.revenue":"Выручка","dashboard.units":"Продано единиц","dashboard.orders":"заказов","dashboard.fullCost":"Полная себестоимость","dashboard.incompleteCoverage":"Неполное покрытие","dashboard.grossProfit":"Валовая прибыль","dashboard.fees":"Комиссии","dashboard.delivery":"Доставка","dashboard.periodExpenses":"Расходы периода","dashboard.expenseKinds":"Прямые и общеорганизационные","dashboard.operatingProfit":"Операционная прибыль","dashboard.operatingMargin":"Операционная маржа","dashboard.noRevenue":"Нет выручки","dashboard.prelimShort":"Предварительно","dashboard.chartTitle":"Выручка и прибыль","dashboard.chartLead":"Динамика по дням","dashboard.profit":"Прибыль","dashboard.dataCompleteness":"Полнота данных","dashboard.costCoverage":"Покрытие себестоимостью","dashboard.revenueWord":"выручки","dashboard.checkProducts":"Проверить товары","dashboard.topProfit":"TOP-10 по прибыли","dashboard.topLoss":"TOP-10 по убытку","dashboard.periodSelected":"За выбранный период","dashboard.loss":"Убыток","dashboard.all":"Все →","dashboard.attention":"Требует внимания","dashboard.accuracyBlockers":"Что мешает точному расчёту","dashboard.noCost":"Нет себестоимости","dashboard.add":"Добавить","dashboard.negativeMargin":"Отрицательная маржа","dashboard.open":"Открыть","dashboard.syncError":"Ошибка синхронизации","dashboard.checkRequired":"Требуется проверка","dashboard.check":"Проверить","dashboard.noProblems":"Проблем за выбранный период нет.",
  "dashboard.missingCostPrefix":"Для","dashboard.missingCostSuffix":"выручки не указана себестоимость.","dashboard.problemCountSuffix":"проблем требует внимания",
} as const;

export type TranslationKey=keyof typeof ru;
const kk:Record<TranslationKey,string>={
  ...ordersKk,
  ...productsKk,
  ...productDetailKk,
  ...financeKk,
  ...exportsKk,
  ...settingsKk,
  ...kaspiKk,
  ...abcKk,
  ...adminKk,
  "brand.name":"Seller Finance","common.wait":"Күте тұрыңыз…","common.logout":"шығу","common.create":"Құру",
  "auth.login.title":"Кіру","auth.login.lead":"Пайда мен өзіндік құнды бір жерден басқарыңыз.","auth.login.submit":"Кіру",
  "auth.register.title":"Тіркелгі ашу","auth.register.lead":"Сатушының қорғалған жұмыс кеңістігін құрыңыз.","auth.register.submit":"Тіркелу","auth.register.name":"Атыңыз","auth.register.organization":"Ұйым атауы",
  "auth.email":"Email","auth.password":"Құпиясөз","auth.forgot.title":"Құпиясөзді қалпына келтіру","auth.forgot.lead":"Тіркелгі бар болса, бір реттік сілтеме жібереміз.","auth.forgot.submit":"Нұсқаулықты жіберу","auth.forgot.link":"Құпиясөзді ұмыттыңыз ба?","auth.forgot.success":"Тіркелгі бар болса, нұсқаулық email-ға жіберілді.","auth.confirm.success":"Поштаңызды тексеріп, email-ды растаңыз.","auth.confirm.deliveryFailed":"Тіркелгі құрылды, бірақ хат әзірге жеткізілмеді. Қайта жіберіп көріңіз.","auth.confirm.resend":"Хатты қайта жіберу","auth.confirm.resent":"Тіркелгі растауды күтсе, хат қайта жіберілді.",
  "auth.switch.login":"Тіркелгіңіз бар ма? Кіру","auth.switch.register":"Тіркелгіңіз жоқ па? Тіркелу","auth.switch.back":"Кіруге оралу","auth.error":"Авторизация қатесі","auth.session.error":"Сессия құрылмады",
  "auth.hero.eyebrow":"Маркетплейс қаржысы айқын көрінеді","auth.hero.title":"Әр тапсырыс пен тауардың нақты пайдасын біліңіз.","auth.hero.lead":"Өзіндік құн, комиссия, жеткізу және шығындар — бір есепте.","demo.banner.title":"Demo режимі","demo.banner.body":"Тек ойдан шығарылған деректерді пайдаланыңыз. Нақты Kaspi қосылымы өшірілген.","demo.auth.title":"Жалпыға қолжетімді демонстрация","demo.auth.body":"Бұл орта сатушылардың, сатып алушылардың нақты деректеріне немесе жарамды Kaspi token-деріне арналмаған.","demo.auth.consent":"Мен тек ойдан шығарылған сынақ деректерін пайдаланамын.",
  "reset.title":"Жаңа құпиясөз","reset.submit":"Құпиясөзді сақтау","reset.success":"Құпиясөз өзгертілді. Енді кіруге болады.","reset.error":"Сілтеме жарамсыз немесе құпиясөз талаптарға сай емес.",
  "nav.dashboard":"Шолу","nav.products":"Тауарлар","nav.orders":"Тапсырыстар","nav.abc":"ABC-талдау","nav.exports":"Экспорт","nav.integrations":"Интеграциялар","nav.expenses":"Шығындар","nav.fees":"Комиссиялар","nav.settings":"Баптаулар","nav.admin":"SaaS Admin","nav.analytics":"ТАЛДАУ","nav.management":"БАСҚАРУ","plan.trial":"Trial тарифі","plan.pilot":"Сынақ кезеңі","plan.organization":"1 ұйым",
  "header.menu":"Мәзірді ашу","header.organization":"Ұйым","header.createOrganization":"Ұйым құру","header.organizationPrompt":"Жаңа ұйымның атауы","header.organizationCreateError":"Ұйымды құру мүмкін болмады","language.ru":"Русский","language.kk":"Қазақша",
  "dashboard.title":"Қаржылық шолу","dashboard.lead":"Таңдалған кезеңдегі сатылым мен пайда туралы негізгі мәлімет.","dashboard.sync":"Синхрондау","dashboard.today":"Бүгін","dashboard.yesterday":"Кеше","dashboard.days7":"Соңғы 7 күн","dashboard.days30":"Соңғы 30 күн","dashboard.days90":"Соңғы 90 күн","dashboard.currentMonth":"Ағымдағы ай","dashboard.previousMonth":"Алдыңғы ай","dashboard.custom":"Еркін кезең","dashboard.periodFrom":"Кезеңнің басы","dashboard.periodTo":"Кезеңнің соңы","dashboard.completeCosts":"Тек толық өзіндік құны бар сатылымдар","dashboard.loaded":"Деректер PostgreSQL-ден жүктелді","dashboard.preliminary":"Пайда алдын ала есептелген","dashboard.fillCosts":"Өзіндік құнды толтыру","dashboard.revenue":"Түсім","dashboard.units":"Сатылған дана","dashboard.orders":"тапсырыс","dashboard.fullCost":"Толық өзіндік құн","dashboard.incompleteCoverage":"Толық емес қамту","dashboard.grossProfit":"Жалпы пайда","dashboard.fees":"Комиссиялар","dashboard.delivery":"Жеткізу","dashboard.periodExpenses":"Кезең шығындары","dashboard.expenseKinds":"Тікелей және жалпы ұйымдық","dashboard.operatingProfit":"Операциялық пайда","dashboard.operatingMargin":"Операциялық маржа","dashboard.noRevenue":"Түсім жоқ","dashboard.prelimShort":"Алдын ала","dashboard.chartTitle":"Түсім және пайда","dashboard.chartLead":"Күндер бойынша динамика","dashboard.profit":"Пайда","dashboard.dataCompleteness":"Деректердің толықтығы","dashboard.costCoverage":"Өзіндік құнмен қамту","dashboard.revenueWord":"түсім","dashboard.checkProducts":"Тауарларды тексеру","dashboard.topProfit":"Пайда бойынша TOP-10","dashboard.topLoss":"Залал бойынша TOP-10","dashboard.periodSelected":"Таңдалған кезеңде","dashboard.loss":"Залал","dashboard.all":"Барлығы →","dashboard.attention":"Назар аудару қажет","dashboard.accuracyBlockers":"Дәл есептеуге кедергілер","dashboard.noCost":"Өзіндік құн жоқ","dashboard.add":"Қосу","dashboard.negativeMargin":"Теріс маржа","dashboard.open":"Ашу","dashboard.syncError":"Синхрондау қатесі","dashboard.checkRequired":"Тексеру қажет","dashboard.check":"Тексеру","dashboard.noProblems":"Таңдалған кезеңде мәселе жоқ."
  ,"dashboard.missingCostPrefix":"Өзіндік құны көрсетілмеген","dashboard.missingCostSuffix":"түсім.","dashboard.problemCountSuffix":"мәселе назар аударуды қажет етеді"
};

export type Locale="ru"|"kk";
const catalogs:Record<Locale,Record<TranslationKey,string>>={ru,kk};
type I18nValue={locale:Locale;setLocale:(locale:Locale)=>void;t:(key:TranslationKey)=>string};
const I18nContext=createContext<I18nValue|null>(null);

export function I18nProvider({children}:{children:React.ReactNode}){
  const [locale,setLocaleState]=useState<Locale>(()=>localStorage.getItem("seller-finance-locale")==="kk"?"kk":"ru");
  useEffect(()=>{document.documentElement.lang=locale;},[locale]);
  const value=useMemo<I18nValue>(()=>({locale,setLocale(next){localStorage.setItem("seller-finance-locale",next);document.documentElement.lang=next;setLocaleState(next);},t:key=>catalogs[locale][key]}),[locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(){const value=useContext(I18nContext);if(!value)throw new Error("I18nProvider is required");return value;}
