import {useEffect,useState} from 'react'
import {RefreshCw,ShieldCheck,Store,Trash2} from 'lucide-react'
import {useI18n} from './i18n'

type Props={session:{organizationId:string;role:string;plan:string;marketplaceConnectionsEnabled?:boolean}}
type Connection={id:string;displayName:string;status:string;lastVerifiedAt?:string;lastSuccessfulSyncAt?:string;lastErrorCode?:string;lastJob?:{id:string;status:string;processedOrders:number;changedOrders:number;importedOrders:number;errorCode?:string;createdAt:string}}
type State={items:Connection[];maxStores:number;activeStores:number}

export function KaspiConnections({session}:Props){
 const {t,locale}=useI18n(),localeCode=locale==='kk'?'kk-KZ':'ru-RU'
 const headers:Record<string,string>={},[state,setState]=useState<State>({items:[],maxStores:1,activeStores:0}),[busy,setBusy]=useState(''),[message,setMessage]=useState('');const enabled=session.marketplaceConnectionsEnabled!==false,canManage=enabled&&(session.role==='Owner'||session.role==='Admin'),canWrite=enabled&&session.role!=='Viewer'
 const load=async()=>{try{const response=await fetch('/api/v1/kaspi/connections',{headers});if(response.ok){setState(await response.json());return true}}catch{}setMessage(t('kaspi.loadError'));return false}
 useEffect(()=>{load()},[])
 const result=async(request:Promise<Response>,success:string)=>{try{const response=await request,data=await response.json().catch(()=>null);setMessage(response.ok?success:data?.title||data?.detail||t('kaspi.operationError'));if(response.ok)await load();setBusy('');return response.ok}catch{setMessage(t('kaspi.operationError'));setBusy('');return false}}
 const connect=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy('connect');const formElement=e.currentTarget,form=new FormData(formElement);if(await result(fetch('/api/v1/kaspi/connections',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({displayName:form.get('displayName'),token:form.get('token')})}),t('kaspi.connected')))formElement.reset()}
 const action=async(connection:Connection,type:'sync'|'verify')=>{setBusy(connection.id+type);await result(fetch(`/api/v1/kaspi/connections/${connection.id}/${type}`,{method:'POST',headers}),type==='sync'?t('kaspi.syncQueued'):t('kaspi.tokenValid'))}
 const replace=async(connection:Connection)=>{const token=window.prompt(`${t('kaspi.newTokenPrompt')} «${connection.displayName}»:`);if(!token)return;setBusy(connection.id+'token');await result(fetch(`/api/v1/kaspi/connections/${connection.id}/token`,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({token})}),t('kaspi.tokenReplaced'))}
 const disconnect=async(connection:Connection)=>{if(!window.confirm(`${t('kaspi.disconnectConfirmPrefix')} «${connection.displayName}»? ${t('kaspi.disconnectConfirmSuffix')}`))return;setBusy(connection.id+'delete');await result(fetch(`/api/v1/kaspi/connections/${connection.id}`,{method:'DELETE',headers}),t('kaspi.disconnected'))}
 const statusLabel=(status?:string)=>status?({PendingVerification:t('kaspi.pendingVerification'),Active:t('kaspi.active'),RequiresAttention:t('kaspi.requiresAttention'),Disabled:t('kaspi.disabled'),Queued:t('kaspi.queued'),Running:t('kaspi.running'),Succeeded:t('kaspi.succeeded'),RetryScheduled:t('kaspi.retryScheduled')}[status]||status):'—'
 return <section className="content"><div className="title-row"><div><span className="eyebrow">{t('kaspi.eyebrow')}</span><h1>{t('kaspi.title')}</h1><p>{t('kaspi.plan')} {session.plan}: {t('kaspi.connectedCount')} {state.activeStores} {t('kaspi.of')} {state.maxStores}. {t('kaspi.securityLead')}</p></div></div>{message&&<p className="integration-message">{message}</p>}<div className="connections-grid">{state.items.map(connection=><article className="integration-card store-card" key={connection.id}><div className="integration-status"><span className="orgmark"><Store size={20}/></span><div><b>{connection.displayName}</b><small>{t('kaspi.status')}: {statusLabel(connection.status)}</small></div></div><dl><div><dt>{t('kaspi.lastVerification')}</dt><dd>{connection.lastVerifiedAt?new Date(connection.lastVerifiedAt).toLocaleString(localeCode):'—'}</dd></div><div><dt>{t('kaspi.lastSync')}</dt><dd>{connection.lastSuccessfulSyncAt?new Date(connection.lastSuccessfulSyncAt).toLocaleString(localeCode):'—'}</dd></div><div><dt>{t('kaspi.lastJob')}</dt><dd>{statusLabel(connection.lastJob?.status)}{connection.lastJob?.processedOrders?` · ${connection.lastJob.processedOrders} ${t('kaspi.orders')}`:''}{connection.lastJob?.changedOrders?` (${connection.lastJob.changedOrders} ${t('financial.updates')})`:''}</dd></div>{connection.lastErrorCode&&<div><dt>{t('kaspi.safeError')}</dt><dd>{connection.lastErrorCode}</dd></div>}</dl>{connection.status!=='Disabled'&&<div className="store-actions">{canWrite&&<button className="primary" onClick={()=>action(connection,'sync')} disabled={!!busy}><RefreshCw/>{t('kaspi.sync')}</button>}{canManage&&<><button onClick={()=>action(connection,'verify')} disabled={!!busy}><ShieldCheck/>{t('kaspi.verify')}</button><button onClick={()=>replace(connection)} disabled={!!busy}>{t('kaspi.replaceToken')}</button><button className="text-danger" onClick={()=>disconnect(connection)} disabled={!!busy}><Trash2/>{t('kaspi.disconnect')}</button></>}</div>}</article>)}</div>{canManage&&state.activeStores<state.maxStores&&<article className="entry-card connect-store"><h2>{t('kaspi.connectTitle')}</h2><form className="token-form" onSubmit={connect}><label>{t('kaspi.storeName')}<input name="displayName" required minLength={2} maxLength={80} placeholder={t('kaspi.storeExample')}/></label><label>{t('kaspi.apiToken')}<input name="token" type="password" required autoComplete="off" placeholder={t('kaspi.tokenPlaceholder')}/></label><button className="primary" disabled={!!busy}>{busy==='connect'?t('kaspi.checking'):t('kaspi.verifyConnect')}</button></form></article>}{!state.items.length&&<div className="empty-row">{t('kaspi.empty')}</div>}</section>
}
