import {useEffect,useState} from 'react'
import {RefreshCw,ShieldCheck,Store,Trash2} from 'lucide-react'

type Props={session:{organizationId:string;role:string;plan:string}}
type Connection={id:string;displayName:string;status:string;lastVerifiedAt?:string;lastSuccessfulSyncAt?:string;lastErrorCode?:string;lastJob?:{id:string;status:string;importedOrders:number;errorCode?:string;createdAt:string}}
type State={items:Connection[];maxStores:number;activeStores:number}

export function KaspiConnections({session}:Props){
 const headers={'X-Organization-Id':session.organizationId},[state,setState]=useState<State>({items:[],maxStores:1,activeStores:0}),[busy,setBusy]=useState(''),[message,setMessage]=useState('');const canManage=session.role==='Owner'||session.role==='Admin'
 const load=()=>fetch('/api/v1/kaspi/connections',{headers}).then(r=>r.ok?r.json():Promise.reject()).then(setState)
 useEffect(()=>{load()},[])
 const result=async(response:Response,success:string)=>{const data=await response.json().catch(()=>null);setMessage(response.ok?success:data?.title||data?.detail||'Операция не выполнена');if(response.ok)await load();setBusy('');return response.ok}
 const connect=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy('connect');const formElement=e.currentTarget,form=new FormData(formElement);if(await result(await fetch('/api/v1/kaspi/connections',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({displayName:form.get('displayName'),token:form.get('token')})}),'Магазин подключён'))formElement.reset()}
 const action=async(connection:Connection,type:'sync'|'verify')=>{setBusy(connection.id+type);await result(await fetch(`/api/v1/kaspi/connections/${connection.id}/${type}`,{method:'POST',headers}),type==='sync'?'Синхронизация поставлена в очередь':'Токен действителен')}
 const replace=async(connection:Connection)=>{const token=window.prompt(`Новый API-токен для «${connection.displayName}»:`);if(!token)return;setBusy(connection.id+'token');await result(await fetch(`/api/v1/kaspi/connections/${connection.id}/token`,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({token})}),'Токен заменён')}
 const disconnect=async(connection:Connection)=>{if(!window.confirm(`Отключить магазин «${connection.displayName}»? Исторические заказы сохранятся.`))return;setBusy(connection.id+'delete');await result(await fetch(`/api/v1/kaspi/connections/${connection.id}`,{method:'DELETE',headers}),'Магазин отключён')}
 return <section className="content"><div className="title-row"><div><span className="eyebrow">ИНТЕГРАЦИИ</span><h1>Kaspi Магазины</h1><p>Тариф {session.plan}: подключено {state.activeStores} из {state.maxStores}. Токены шифруются и обратно не отображаются.</p></div></div>{message&&<p className="integration-message">{message}</p>}<div className="connections-grid">{state.items.map(connection=><article className="integration-card store-card" key={connection.id}><div className="integration-status"><span className="orgmark"><Store size={20}/></span><div><b>{connection.displayName}</b><small>Статус: {connection.status}</small></div></div><dl><div><dt>Последняя проверка</dt><dd>{connection.lastVerifiedAt?new Date(connection.lastVerifiedAt).toLocaleString('ru-RU'):'—'}</dd></div><div><dt>Последняя синхронизация</dt><dd>{connection.lastSuccessfulSyncAt?new Date(connection.lastSuccessfulSyncAt).toLocaleString('ru-RU'):'—'}</dd></div><div><dt>Последнее задание</dt><dd>{connection.lastJob?.status||'—'}{connection.lastJob?.importedOrders?` · ${connection.lastJob.importedOrders} заказов`:''}</dd></div>{connection.lastErrorCode&&<div><dt>Безопасная ошибка</dt><dd>{connection.lastErrorCode}</dd></div>}</dl>{connection.status!=='Disabled'&&<div className="store-actions"><button className="primary" onClick={()=>action(connection,'sync')} disabled={!!busy}><RefreshCw/>Синхронизировать</button>{canManage&&<><button onClick={()=>action(connection,'verify')} disabled={!!busy}><ShieldCheck/>Проверить</button><button onClick={()=>replace(connection)} disabled={!!busy}>Заменить token</button><button className="text-danger" onClick={()=>disconnect(connection)} disabled={!!busy}><Trash2/>Отключить</button></>}</div>}</article>)}</div>{canManage&&state.activeStores<state.maxStores&&<article className="entry-card connect-store"><h2>Подключить магазин</h2><form className="token-form" onSubmit={connect}><label>Название магазина<input name="displayName" required minLength={2} maxLength={80} placeholder="Например, Основной магазин"/></label><label>API-токен Kaspi<input name="token" type="password" required autoComplete="off" placeholder="Токен из кабинета продавца"/></label><button className="primary" disabled={!!busy}>{busy==='connect'?'Проверяем…':'Проверить и подключить'}</button></form></article>}{!state.items.length&&<div className="empty-row">Подключённых магазинов пока нет.</div>}</section>
}
