import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BarChart3, Box, ChevronDown, CircleAlert, Download, LayoutDashboard, LogIn, Menu, PackageSearch, RefreshCw, Search, Settings, ShoppingBag, Sparkles, TrendingDown, TrendingUp, WalletCards, X } from 'lucide-react'
import './styles.css'

type Summary = { revenue:number; orders:number; units:number; cogs:number|null; grossProfit:number; marketplaceFees:number; delivery:number; operatingProfit:number; operatingMarginPct:number|null; coveragePct:number; isPreliminary:boolean }
type Product = { id:string; sku:string; name:string; units:number; revenue:number; cogs:number|null; profit:number|null; margin:number|null; cost:number|null; coveragePct?:number; status:string }
type Point = { date:string; revenue:number; profit:number }
type Page = 'dashboard'|'products'|'orders'|'abc'|'integrations'
type Session = { userId:string; email:string; displayName:string; organizationId:string; organizationName:string; role:string; plan:string }
type Order = { id:string; date:string; status:string; amount:number; items:number; complete:boolean }

const fallback:{summary:Summary; products:Product[]; timeseries:Point[]} = {
  summary:{revenue:173835,orders:6,units:12,cogs:null,grossProfit:83835,marketplaceFees:17798,delivery:3850,operatingProfit:49687,operatingMarginPct:28.58,coveragePct:92.53,isPreliminary:true},
  products:[
    {id:'p1',sku:'HOME-101',name:'Органайзер для кухни',units:5,revenue:62475,cogs:36000,profit:18865,margin:30.2,cost:7200,status:'profitable'},
    {id:'p2',sku:'BEAUTY-220',name:'Набор косметичек',units:3,revenue:55470,cogs:26700,profit:22173,margin:40,cost:8900,status:'profitable'},
    {id:'p3',sku:'TECH-044',name:'Настольная LED-лампа',units:3,revenue:42900,cogs:27300,profit:10400,margin:24.2,cost:9100,status:'profitable'},
    {id:'p4',sku:'KIDS-018',name:'Развивающий набор',units:1,revenue:12990,cogs:null,profit:null,margin:null,cost:null,status:'missing-cost'}],
  timeseries:[{date:'2026-08-06',revenue:24990,profit:7166},{date:'2026-08-07',revenue:18490,profit:7124},{date:'2026-08-08',revenue:42900,profit:10400},{date:'2026-08-09',revenue:12990,profit:1051},{date:'2026-08-10',revenue:37485,profit:10999},{date:'2026-08-11',revenue:36980,profit:13850}]
}

const money=(v:number|null)=>v===null?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v)+' ₸'
const pct=(v:number|null)=>v===null?'—':v.toFixed(1).replace('.',',')+'%'

function App(){
  const [page,setPage]=useState<Page>('dashboard'), [menu,setMenu]=useState(false), [loading,setLoading]=useState(true)
  const [session,setSession]=useState<Session|null>(null), [authReady,setAuthReady]=useState(false)
  const [summary,setSummary]=useState(fallback.summary), [products,setProducts]=useState(fallback.products), [points,setPoints]=useState(fallback.timeseries)
  const [orders,setOrders]=useState<Order[]>([])
  useEffect(()=>{ fetch('/api/v1/session').then(async r=>r.ok?setSession(await r.json()):setSession(null)).finally(()=>setAuthReady(true)) },[])
  useEffect(()=>{ if(!session)return; const headers={'X-Organization-Id':session.organizationId}; Promise.all([
    fetch('/api/v1/analytics/summary',{headers}).then(r=>r.ok?r.json():Promise.reject()),
    fetch('/api/v1/analytics/products',{headers}).then(r=>r.ok?r.json():Promise.reject()),
    fetch('/api/v1/analytics/timeseries',{headers}).then(r=>r.ok?r.json():Promise.reject()),
    fetch('/api/v1/orders',{headers}).then(r=>r.ok?r.json():Promise.reject())
  ]).then(([s,p,t,o])=>{setSummary(s);setProducts(p);setPoints(t);setOrders(o)}).catch(()=>{}).finally(()=>setLoading(false)) },[session])
  if(!authReady)return <div className="auth-loading">Seller Finance</div>
  if(!session)return <AuthScreen onAuthenticated={setSession}/>
  const navigate=(p:Page)=>{setPage(p);setMenu(false)}
  return <div className="app">
    <Sidebar page={page} open={menu} onClose={()=>setMenu(false)} onNav={navigate}/>
    <main>
      <header><button className="icon mobile" onClick={()=>setMenu(true)} aria-label="Открыть меню"><Menu/></button><div className="org"><span className="orgmark">{session.organizationName[0]}</span><div><b>{session.organizationName}</b><small>{session.role}</small></div><ChevronDown size={16}/></div><div className="head-actions"><button className="icon"><Search/></button><button className="avatar" title={`${session.email} — выйти`} onClick={async()=>{await fetch('/api/v1/auth/logout',{method:'POST'});setSession(null)}}>{(session.displayName||session.email).slice(0,2).toUpperCase()}</button></div></header>
      {page==='dashboard'&&<Dashboard summary={summary} products={products} points={points} loading={loading}/>} 
      {page==='products'&&<Products products={products} session={session}/>}
      {page==='orders'&&<Orders orders={orders}/>}
      {page==='abc'&&<EmptyPage title="ABC-анализ" text="Товары будут распределены по вкладу в операционную прибыль." icon={<BarChart3/>}/>} 
      {page==='integrations'&&<Integrations session={session}/>}
    </main>
  </div>
}

function AuthScreen({onAuthenticated}:{onAuthenticated:(session:Session)=>void}){
 const [register,setRegister]=useState(false), [busy,setBusy]=useState(false), [error,setError]=useState('')
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const body=register?{email:form.get('email'),password:form.get('password'),displayName:form.get('displayName'),organizationName:form.get('organizationName')}:{email:form.get('email'),password:form.get('password')};try{const response=await fetch(`/api/v1/auth/${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){const data=await response.json().catch(()=>null);throw new Error(data?.message||data?.title||'Не удалось войти')}const sessionResponse=await fetch('/api/v1/session');if(!sessionResponse.ok)throw new Error('Сессия не создана');onAuthenticated(await sessionResponse.json())}catch(ex){setError(ex instanceof Error?ex.message:'Ошибка авторизации')}finally{setBusy(false)}}
 return <div className="auth-page"><section className="auth-panel"><div className="auth-brand"><span><WalletCards/></span><div>Seller<b>Finance</b></div></div><h1>{register?'Создать аккаунт':'Войти'}</h1><p>{register?'Создайте защищённое рабочее пространство продавца.':'Управляйте прибылью и себестоимостью в одном месте.'}</p><form onSubmit={submit}>{register&&<><label>Ваше имя<input name="displayName" required autoComplete="name"/></label><label>Название организации<input name="organizationName" required/></label></>}<label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Пароль<input name="password" type="password" minLength={8} required autoComplete={register?'new-password':'current-password'}/></label>{error&&<div className="auth-error">{error}</div>}<button className="primary" disabled={busy}><LogIn/>{busy?'Подождите…':register?'Зарегистрироваться':'Войти'}</button></form><button className="auth-switch" onClick={()=>{setRegister(!register);setError('')}}>{register?'Уже есть аккаунт? Войти':'Нет аккаунта? Зарегистрироваться'}</button></section><aside className="auth-hero"><span>Финансы маркетплейса без слепых зон</span><h2>Знайте реальную прибыль каждого заказа и товара.</h2><p>Себестоимость, комиссии, доставка и расходы — в едином расчёте.</p></aside></div>
}

function Sidebar({page,open,onClose,onNav}:{page:Page;open:boolean;onClose:()=>void;onNav:(p:Page)=>void}){
 const nav:[Page,string,React.ReactNode][]=[['dashboard','Обзор',<LayoutDashboard/>],['products','Товары',<Box/>],['orders','Заказы',<ShoppingBag/>],['abc','ABC-анализ',<BarChart3/>]]
 return <><aside className={open?'open':''}><div className="brand"><span><WalletCards/></span><div>Seller<b>Finance</b></div><button className="icon mobile" onClick={onClose}><X/></button></div><nav><small>АНАЛИТИКА</small>{nav.map(([id,label,icon])=><button key={id} className={page===id?'active':''} onClick={()=>onNav(id)}>{icon}{label}</button>)}<small>УПРАВЛЕНИЕ</small><button className={page==='integrations'?'active':''} onClick={()=>onNav('integrations')}><RefreshCw/>Интеграции<span className="dot"/></button><button><Settings/>Настройки</button></nav><div className="plan"><div><Sparkles size={16}/>Тариф Trial</div><b>Пилотный период</b><span><i/></span><small>1 организация</small></div></aside>{open&&<div className="shade" onClick={onClose}/>}</>
}

function Dashboard({summary,products,points,loading}:{summary:Summary;products:Product[];points:Point[];loading:boolean}){
 const max=Math.max(...points.map(x=>x.revenue)); const problems=products.filter(x=>x.cost===null)
 return <section className="content">
  <div className="title-row"><div><span className="eyebrow">12 августа 2026</span><h1>Финансовый обзор</h1><p>Главное о продажах и прибыли за выбранный период.</p></div><div className="actions"><button className="secondary"><Download/>Экспорт</button><button className="primary"><RefreshCw className={loading?'spin':''}/>Синхронизировать</button></div></div>
  <div className="toolbar"><button>Последние 7 дней <ChevronDown/></button><span>06 авг — 12 авг</span><span className="sync"><i/> Данные обновлены 4 мин назад</span></div>
  {summary.isPreliminary&&<div className="notice"><CircleAlert/><div><b>Прибыль предварительная</b><span>Для {money(summary.revenue*(100-summary.coveragePct)/100)} выручки не указана себестоимость.</span></div><button>Заполнить себестоимость</button></div>}
  <div className="kpis"><Kpi label="Выручка" value={money(summary.revenue)} delta="+12,4%" good/><Kpi label="Операционная прибыль" value={money(summary.operatingProfit)} delta="+8,7%" good/><Kpi label="Маржинальность" value={pct(summary.operatingMarginPct)} delta="−1,2 п.п."/><Kpi label="Заказы" value={String(summary.orders)} sub={`${summary.units} единиц`}/></div>
  <div className="grid"><article className="chart-card"><div className="card-head"><div><h2>Выручка и прибыль</h2><p>Динамика по дням</p></div><div className="legend"><span><i className="revenue"/>Выручка</span><span><i className="profit"/>Прибыль</span></div></div><div className="chart">{points.map(p=><div className="bar-col" key={p.date}><div className="bars"><i className="profit-bar" style={{height:`${p.profit/max*100}%`}}/><i className="revenue-bar" style={{height:`${p.revenue/max*100}%`}}/></div><small>{new Date(p.date).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})}</small></div>)}</div></article>
   <article className="coverage"><div className="card-head"><div><h2>Полнота данных</h2><p>Покрытие себестоимостью</p></div></div><div className="ring" style={{'--pct':`${summary.coveragePct*3.6}deg`} as React.CSSProperties}><div><b>{pct(summary.coveragePct)}</b><span>выручки</span></div></div><p><i/> {problems.length} товар требует внимания</p><button>Проверить товары <span>→</span></button></article>
  </div>
  <div className="bottom-grid"><article className="table-card"><div className="card-head"><div><h2>Товары по прибыли</h2><p>За выбранный период</p></div><button>Все товары →</button></div><ProductTable products={products.slice(0,4)}/></article><article className="problems"><div className="card-head"><div><h2>Требует внимания</h2><p>Что мешает точному расчёту</p></div><span>{problems.length}</span></div>{problems.map(p=><div className="problem" key={p.id}><PackageSearch/><div><b>Нет себестоимости</b><span>{p.name} · {p.sku}</span></div><button>Добавить</button></div>)}<div className="problem warning"><TrendingDown/><div><b>Маржа снизилась</b><span>Набор косметичек · −4,1 п.п.</span></div><button>Открыть</button></div></article></div>
 </section>
}

function Kpi({label,value,delta,sub,good}:{label:string;value:string;delta?:string;sub?:string;good?:boolean}){return <article className="kpi"><span>{label}</span><b>{value}</b><div className={good?'good':''}>{good?<TrendingUp/>:delta?<TrendingDown/>:null}{delta&&<strong>{delta}</strong>}{sub&&<small>{sub}</small>}{delta&&<small>к прошлой неделе</small>}</div></article>}
function Orders({orders}:{orders:Order[]}){return <section className="content"><div className="title-row"><div><span className="eyebrow">ПРОДАЖИ</span><h1>Заказы</h1><p>Заказы Kaspi и полнота финансового расчёта.</p></div></div><article className="table-card standalone"><div className="table-wrap"><table><thead><tr><th>Заказ</th><th>Дата</th><th>Статус</th><th>Позиций</th><th>Сумма</th><th>Расчёт</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.id}</td><td>{new Date(o.date).toLocaleDateString('ru-RU')}</td><td>{o.status}</td><td>{o.items}</td><td>{money(o.amount)}</td><td><span className={o.complete?'pill':'pill missing'}>{o.complete?'Полный':'Нужна себестоимость'}</span></td></tr>)}</tbody></table>{orders.length===0&&<div className="empty-row">Заказов пока нет. Подключите Kaspi и выполните синхронизацию.</div>}</div></article></section>}

function Integrations({session}:{session:Session}){
 const [state,setState]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const headers={'X-Organization-Id':session.organizationId};
 const load=()=>fetch('/api/v1/kaspi/connection',{headers}).then(r=>r.json()).then(setState);useEffect(()=>{load()},[]);
 const connect=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage('');const token=String(new FormData(e.currentTarget).get('token')||'');const r=await fetch('/api/v1/kaspi/connection',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({token})});setMessage(r.ok?'Kaspi успешно подключён.':(await r.json().catch(()=>null))?.detail||'Не удалось проверить токен.');setBusy(false);if(r.ok)load()};
 const sync=async()=>{setBusy(true);const r=await fetch('/api/v1/kaspi/sync',{method:'POST',headers});setMessage(r.ok?'Синхронизация поставлена в очередь.':'Не удалось запустить синхронизацию.');setBusy(false);setTimeout(load,1500)};
 return <section className="content"><div className="title-row"><div><span className="eyebrow">ИНТЕГРАЦИИ</span><h1>Kaspi Магазин</h1><p>Токен шифруется AES-256-GCM и никогда не отображается после сохранения.</p></div></div><article className="integration-card"><div className="integration-status"><span className="orgmark">K</span><div><b>Kaspi Магазин</b><small>{state?.connected?`Статус: ${state.status}`:'Не подключён'}</small></div></div>{state?.connected?<><dl><div><dt>Последняя проверка</dt><dd>{state.lastVerifiedAt?new Date(state.lastVerifiedAt).toLocaleString('ru-RU'):'—'}</dd></div><div><dt>Последняя синхронизация</dt><dd>{state.lastSuccessfulSyncAt?new Date(state.lastSuccessfulSyncAt).toLocaleString('ru-RU'):'—'}</dd></div><div><dt>Задание</dt><dd>{state.lastJob?.status||'—'} {state.lastJob?.importedOrders?`· ${state.lastJob.importedOrders} заказов`:''}</dd></div></dl><button className="primary" onClick={sync} disabled={busy}><RefreshCw className={busy?'spin':''}/>Синхронизировать 30 дней</button></>:<form className="token-form" onSubmit={connect}><label>API-токен Kaspi<input name="token" type="password" required autoComplete="off" placeholder="Вставьте токен из кабинета Kaspi"/></label><button className="primary" disabled={busy}>{busy?'Проверяем…':'Проверить и подключить'}</button></form>}{message&&<p className="integration-message">{message}</p>}</article></section>
}
function ProductTable({products}:{products:Product[]}){return <div className="table-wrap"><table><thead><tr><th>Товар</th><th>Выручка</th><th>Прибыль</th><th>Маржа</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><span className="product-icon">{p.name[0]}</span><div><b>{p.name}</b><small>{p.sku}</small></div></td><td>{money(p.revenue)}</td><td className={p.profit===null?'muted':'positive'}>{money(p.profit)}</td><td><span className={p.margin===null?'pill missing':'pill'}>{pct(p.margin)}</span></td></tr>)}</tbody></table></div>}
function Products({products,session}:{products:Product[];session:Session}){
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<Product|null>(null),[detail,setDetail]=useState<any>(null),[preview,setPreview]=useState<any>(null),[message,setMessage]=useState('');const headers={'X-Organization-Id':session.organizationId};
 const filtered=products.filter(p=>(p.sku+' '+p.name).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='missing'&&p.cost===null||filter==='profitable'&&(p.profit??0)>0||filter==='loss'&&(p.profit??0)<0));
 const open=async(p:Product)=>{setSelected(p);const r=await fetch(`/api/v1/products/${p.id}`,{headers});if(r.ok)setDetail(await r.json())};
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const form=new FormData();form.append('file',file);setMessage('Проверяем файл…');const r=await fetch('/api/v1/costs/imports/preview',{method:'POST',headers,body:form});const data=await r.json();if(r.ok){setPreview(data);setMessage('')}else setMessage(data.title||'Ошибка импорта')};
 const confirm=async()=>{const r=await fetch(`/api/v1/costs/imports/${preview.id}/confirm`,{method:'POST',headers});if(r.ok){const data=await r.json();setMessage(`Применено строк: ${data.appliedRows}`);setPreview(null)}else setMessage('Не удалось применить импорт')};
 const addCost=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);const r=await fetch(`/api/v1/products/${selected.id}/costs`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({cost:Number(f.get('cost')),effectiveFrom:f.get('date')})});if(r.ok){setMessage('Себестоимость добавлена');open(selected)}else setMessage((await r.json().catch(()=>null))?.title||'Ошибка')};
 return <section className="content"><div className="title-row"><div><span className="eyebrow">КАТАЛОГ</span><h1>Товары</h1><p>Продажи, история себестоимости и Coverage по SKU.</p></div><label className="primary file-button">Импорт CSV/XLSX<input type="file" accept=".csv,.xlsx" onChange={upload}/></label></div><div className="product-tools"><input placeholder="Поиск по SKU или названию" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все товары</option><option value="profitable">Прибыльные</option><option value="loss">Убыточные</option><option value="missing">Без себестоимости</option></select></div>{message&&<p className="integration-message">{message}</p>}{preview&&<ImportPreview preview={preview} onConfirm={confirm}/>}<article className="table-card standalone"><div className="table-wrap"><table><thead><tr><th>Товар</th><th>Продажи</th><th>Выручка</th><th>Прибыль</th><th>Маржа</th><th>Coverage</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} onClick={()=>open(p)}><td><span className="product-icon">{p.name[0]}</span><div><b>{p.name}</b><small>{p.sku}</small></div></td><td>{p.units}</td><td>{money(p.revenue)}</td><td>{money(p.profit)}</td><td>{pct(p.margin)}</td><td>{pct(p.coveragePct??(p.cost===null?0:100))}</td></tr>)}</tbody></table></div></article>{selected&&<div className="modal-shade" onClick={()=>setSelected(null)}><article className="product-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">{selected.sku}</span><h2>{selected.name}</h2><form className="cost-form" onSubmit={addCost}><label>Себестоимость<input name="cost" type="number" min="0.01" step="0.01" required/></label><label>Действует с<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><button className="primary">Добавить</button></form><h3>История себестоимости</h3><div className="cost-history">{detail?.costHistory?.map((x:any)=><div key={x.id}><b>{money(x.costAmount)}</b><span>с {new Date(x.effectiveFrom).toLocaleDateString('ru-RU')} · {x.source}</span></div>)}{detail&&!detail.costHistory?.length&&<p>История пока пуста.</p>}</div></article></div>}</section>
}
function ImportPreview({preview,onConfirm}:{preview:any;onConfirm:()=>void}){return <article className="import-preview"><div><h2>Предпросмотр импорта</h2><p>Строк: {preview.totalRows} · найдено: {preview.matchedRows} · не сопоставлено: {preview.unmatchedRows} · ошибки: {preview.errorRows} · дубли: {preview.duplicateRows}</p></div><button className="primary" onClick={onConfirm} disabled={!preview.expectedChanges}>Применить {preview.expectedChanges} изменений</button><div className="table-wrap"><table><thead><tr><th>Строка</th><th>SKU</th><th>Себестоимость</th><th>Дата</th><th>Статус</th></tr></thead><tbody>{preview.rows.map((r:any)=><tr key={r.rowNumber}><td>{r.rowNumber}</td><td>{r.sku}</td><td>{money(r.costAmount)}</td><td>{r.effectiveFrom||'—'}</td><td><span className={r.status==='Valid'?'pill':'pill missing'}>{r.error||r.status}</span></td></tr>)}</tbody></table></div></article>}
function EmptyPage({title,text,icon}:{title:string;text:string;icon:React.ReactNode}){return <section className="content"><div className="empty"><span>{icon}</span><h1>{title}</h1><p>{text}</p><button className="primary">Перейти к интеграциям</button></div></section>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
